apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: openshift-gitops
spec:
  destination:
    namespace: cd-sample-development
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mamoru1112/cd-sample-github.git
    targetRevision: main
    path: overlays/development
  syncPolicy: {}