apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: openshift-gitops
spec:
  destination:
    namespace: cd-sample-production
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mamoru1112/cd-sample-github.git
    targetRevision: main
    path: overlays/production
  syncPolicy: {}